version: '3.8'
services:
  db:
    image: postgres:latest
    container_name: api_vista
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: Vistas
    ports:
      - "5434:5432"
    volumes:
      - db_data:/var/lib/postgresql-/data      
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build:
      context: .
    ports:
      - "8082:8082"
    depends_on:
      - db

volumes:
  db_data:
