name: Test API and Run Postman Tests on Linux

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requeriments_sqlalchemy.txt

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install Newman (Postman CLI)
        run: npm install -g newman

      - name: Build Docker image
        run: |
          docker build -t openapi-server .

      - name: Run Docker container in the background
        run: |
          docker run -d -p 8082:8082 openapi-server

      - name: Wait for server to start
        run: |
          sleep 10

      - name: Run Postman tests with Newman
        run: |
          newman run openapi_server/test/Test_Api_Vistas.postman_collection.json
        env:
          BASE_URL: http://localhost:8082